name: Lint-and-Build-to-Dockerhub

on: push

jobs: 

  super-lint:
    name: Lint code base
    runs-on: ubuntu-latest
    
    
    steps:
      - name: Checkout code
        uses: actions/checkout@v2
        
      - name: Run Super-Linter
        uses: github/super-linter@v3
        env:
          DEFAULT_BRANCH: prod
          GITHUB_TOKEN: ${{ secrets.TOKEN }}
    
    
    docker:
    runs-on: ubuntu-latest
    steps:
      -
        name: Aet up QEMU
        uses: docker/setup-qemu-action@v1
      -
        name: Set up Docker Buildx
        uses: docker/setup-bulidx-action@v1
      -
        name: Login to DockerHub
        uses: docker/login-action@v1
        with: 
          username: ${{ secrets.DOCKERHUB_USERNAME }}
          password: ${{ secrets.DOCKERHUB_TOKEN }}
      -
        name: Build and push
        id: docker_build
        uses: docker/build-push-action@v2
        with:
          push: true
          tags: Zografska/ciii_proj:latest
      - 
        name: Image digest
        run: echo ${{ steps.docker_build.outputs.digest }}
